# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
