# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_auto_20161009_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='codigo_de_rastreo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='empresa_envio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
